map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen 80;
  server_name global.example.com a.example.com b.example.com keycloak.example.com pgadmin.example.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name global.example.com;

  ssl_certificate /etc/nginx/certs/_wildcard.example.com.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.example.com-key.pem;

  location /login {
    proxy_pass http://bff-global:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location /auth/ {
    proxy_pass http://bff-global:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location / {
    proxy_pass http://frontend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}

server {
  listen 443 ssl http2;
  server_name a.example.com;

  ssl_certificate /etc/nginx/certs/_wildcard.example.com.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.example.com-key.pem;

  location / {
    proxy_pass http://bff-a:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}

server {
  listen 443 ssl http2;
  server_name b.example.com;

  ssl_certificate /etc/nginx/certs/_wildcard.example.com.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.example.com-key.pem;

  location / {
    proxy_pass http://bff-b:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}

server {
  listen 443 ssl http2;
  server_name keycloak.example.com;

  ssl_certificate /etc/nginx/certs/_wildcard.example.com.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.example.com-key.pem;

  location / {
    proxy_pass http://keycloak:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}

server {
  listen 443 ssl http2;
  server_name pgadmin.example.com;

  ssl_certificate /etc/nginx/certs/_wildcard.example.com.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.example.com-key.pem;

  location / {
    proxy_pass http://pgadmin:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}
